version: '3.8'

services:
  task-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-management:latest
    container_name: task-management-instance
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET=3hLpHI+TogwrhC8JWviTinLEDreHNyuEPx5b0ddvd9k6t/WglvANd3lj5slyYAZzrKFFmFSqEt0HJeeZFv76RiUFe6S1c9/kKnm03Sce6JxFJgfYT7sHi6oMf92gxw3p8WTf2AG3gpjxP5UWkKuUp9VbCnQPMHDWBEweYNG0xvxnMoNGPZWOtHbXH292YMOgPL1Mm8q4dBydcCyT25POTB9voRydudd9Xu6BsBbgpNB+BGRffLA6HFmR00R9bkfD0uGC/43QgGk3OGuokfyqt55nyuG8W/O0YjCLwTcXtNH0+JvxR49A04BeicQdPBpRmZdMSlH18ju9aypfO5ev0BgCQ6GZ6XgiFKxrEaq3rMg=
    networks:
      - task-management-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=taskmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge

volumes:
  postgres-data:
