spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskmanagement}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:3hLpHI+TogwrhC8JWviTinLEDreHNyuEPx5b0ddvd9k6t/WglvANd3lj5slyYAZzrKFFmFSqEt0HJeeZFv76RiUFe6S1c9/kKnm03Sce6JxFJgfYT7sHi6oMf92gxw3p8WTf2AG3gpjxP5UWkKuUp9VbCnQPMHDWBEweYNG0xvxnMoNGPZWOtHbXH292YMOgPL1Mm8q4dBydcCyT25POTB9voRydudd9Xu6BsBbgpNB+BGRffLA6HFmR00R9bkfD0uGC/43QgGk3OGuokfyqt55nyuG8W/O0YjCLwTcXtNH0+JvxR49A04BeicQdPBpRmZdMSlH18ju9aypfO5ev0BgCQ6GZ6XgiFKxrEaq3rMg=}